name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create .env file
      run: |
        echo "NEXT_PUBLIC_GTM=${{ secrets.NEXT_PUBLIC_GTM }}" >> .env
        echo "NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }}" >> .env
        echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
        echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
        echo "GMAIL_PASSKEY=${{ secrets.GMAIL_PASSKEY }}" >> .env
        echo "EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}" >> .env

    - name: Run linting
      run: npm run lint

    - name: Build application
      run: npm run build

    - name: Export static files
      run: npm run build